### ISSUE TITLE
asset download: output zip naming

### ISSUE THREAD

**Issue by graphific** [up42/up42-py#350]
In 0.21.0 `asset.download(output_directory=tmp_dir, unpacking=False)` gave as output `output.tgz`, whereas now in 0.23.0 the output is `output..zip`(with the double .).

Would be nice to have a consistent naming here, or better yet make it possible to pass an output filename or set the zip to the asset name by default?

Keep up the good work!

**Comment by chrieke** [comment]
@graphific Thank you for the issue and kind words! 

The double `.` issue when selecting `unpacking=False` was introduced in 0.22.2 and not caught by the tests. I just released a new version [0.23.1](https://sdk.up42.com/CHANGELOG/#0231-2022-10-05) where this issue is fixed. Please update via `pip install up42-py --upgrade`.

Re the `tgz` & `zip` suffix, unfortunately UP42 currently doesn't deliver assets in a consistent archive schema, the downloaded file can be both `tgz` or `zip`.  We are currently working on improving the user storage experience and I forwarded the feedback. Having the asset-id as the filename is another good suggestion, we will evaluate if maybe better done on backend than the SDK code. Thanks for the suggestions!
